language: csharp
solution: csharp/csharp.sln
mono: none
dotnet: 3.1
jobs:
  include:
    - stage: "Build"
      script:
        - dotnet restore
        - dotnet build
    - stage: "Test"
      script:
        - dotnet test
