language: csharp
mono: none
dotnet: 3.1
jobs:
  include:
    - stage: "Build"
      script:
        - cd csharp
        - dotnet restore
        - dotnet build
    - stage: "Test"
      script:
        - dotnet test
